FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive
ENV container docker
ENV MTR_TYPE host

RUN apt-get -yq update

RUN apt-get -yq install \
    python \
    python-pip \
    virtualenv \
    gunicorn \
    python-flask-sockets \
    curl \
    nginx-full \
    git

COPY scripts/default.site /etc/nginx/sites-available/default
COPY scripts/launch /usr/bin/launch

WORKDIR /mtr-web

RUN git clone https://github.com/thinguy/mtr-web

EXPOSE 8000

CMD /usr/bin/launch

